apiVersion: v1
kind: Pod
metadata:
  name: fortune-subpathexpr
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
#          fieldPath: status.podIP
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -c
          - "ls /usr/share/nginx/html/quote || (apk add fortune && fortune > /usr/share/nginx/html/quote)"
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: content
      mountPath: /usr/share/nginx/html
      subPathExpr: $(POD_NAME)
  volumes:
  - name: content
    hostPath:
      path: /tmp/fortune
