apiVersion: v1
kind: Pod
metadata:
  name: fortune-no-volume
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -c
          - "apk add fortune && fortune > /usr/share/nginx/html/quote"
      preStop:
        exec:
          command:
          - nginx
          - -s
          - quit
    livenessProbe:
      httpGet:
        path: /fortune
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 1
      failureThreshold: 1
    ports:
    - name: http
      containerPort: 80
