apiVersion: v1
kind: Pod
metadata:
  name: fortune-nfs
spec:
  initContainers:
  - name: fortune
    image: luksa/fortune-generator:1.0
    imagePullPolicy: Always
    volumeMounts:
    - name: content
      mountPath: /var/local/output
      readOnly: false
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: content
      mountPath: /usr/share/nginx/html
      readOnly: true
  volumes:
  - name: content
    nfs:
      server: 10.244.2.47
#      server: 10.244.1.87
      path: /exports


# need to run: docker exec -it kind-worker sh -c "apt-get update && apt-get install nfs-client"