apiVersion: v1
kind: Pod
metadata:
  generateName: mongodb-
spec:
  volumes:
  - name: mongodb-data
    hostPath:
      path: /tmp/mongodb-shared
      type: DirectoryOrCreate
  containers:
  - name: mongodb
    image: mongo
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
      subPathExpr: $(HOSTNAME)


