apiVersion: v1
kind: Pod
metadata:
  name: mongodb2
spec:
  nodeName: gke-kubia-default-pool-f0d75bcc-1b27
  volumes:
  - name: mongodb-data
    gcePersistentDisk:
      pdName: mongodb
      fsType: ext4
  containers:
  - name: mongodb
    image: mongo
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP

