apiVersion: v1
kind: Pod
metadata:
  name: nfs-server2
spec:
  containers:
  - name: nfs-server-container
    image: cpuguy83/nfs-server
    securityContext:
      privileged: true
    args:
    # Pass the paths to share to the Docker image
    - /exports